# Generated by Django 3.2.8 on 2021-10-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='saida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
