# Generated by Django 3.2.8 on 2021-10-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20211021_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='ControleCaixa',
        ),
    ]
