# Generated by Django 3.2.8 on 2021-10-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_rename_person_controlecaixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecaixa',
            name='entrada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
