# Generated by Django 3.2.8 on 2021-11-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_alter_controlecaixa_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecaixa',
            name='entrada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='controlecaixa',
            name='saida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
