# Generated by Django 3.2.8 on 2021-11-05 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_auto_20211105_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecaixa',
            name='data_fluxo',
            field=models.DateField(default=datetime.datetime(2021, 11, 5, 19, 4, 45, 131332)),
        ),
    ]
