# Generated by Django 3.2.8 on 2021-11-05 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_alter_controlecaixa_data_fluxo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecaixa',
            name='data_fluxo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
